#!/bin/bash

# Get the current branch name
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Define regex patterns for each branch type
feature_regex="^ft\/[a-z0-9-]+-#MLSPC-[0-9]+$"
chore_regex="^ch\/[a-z0-9-]+-#MLSPC-[0-9]+$"
docs_regex="^docs\/[a-z0-9-]+$"
hotfix_regex="^hotFix\/[a-z0-9-]+$"
bugfix_regex="^bugFix\/[a-z0-9-]+$"
develop_branch="develop"

# Allow push if on develop branch
# if [[ "$branch_name" == "$develop_branch" ]]; then
#   echo "✅ Pushing to the develop branch is allowed. "  #this is temporary since the project is first initiated
#   exit 0
# fi

# Check if the branch name matches any allowed pattern
if [[ $branch_name =~ $feature_regex ]] || [[ $branch_name =~ $chore_regex ]] || \
   [[ $branch_name =~ $docs_regex ]] || [[ $branch_name =~ $hotfix_regex ]] || \
   [[ $branch_name =~ $bugfix_regex ]]; then
  echo "✅ Branch name '$branch_name' is valid."
  exit 0
else
  echo "❌ Branch name '$branch_name' is invalid."
  echo "Allowed branch formats:"
  echo " - Feature branch: 'ft/feature-description-#US-123'"
  echo " - Chore branch: 'ch/chore-description-#US-123'"
  echo " - Documentation branch: 'docs/description'"
  echo " - Hotfix branch: 'hotFix/description'"
  echo " - Bugfix branch: 'bugFix/description'"
  echo " - Develop branch: 'develop'"
  exit 1
fi
